name: Build
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
    - name: Create documentation
    uses: andstor/jsdoc-action@v1
    with:
      source_dir: ./src
      recurse: true
      output_dir: ./out